#    _____ _                  _____ _           _
#   / ____| |                / ____| |         | |
#  | |    | | ___  __ _ _ __| |    | |__   __ _| |_
#  | |    | |/ _ \/ _  |  __| |    |  _ \ / _  | __|
#  | |____| |  __/ (_| | |  | |____| | | | (_| | |_
#   \_____|_|\___|\__ _|_|   \_____|_| |_|\__ _|\__|
#       By YazdanPlug

# The placeholder is %player% which is the player that cleared the chat.
# If you do not want a message to appear after you clear the chat just set it to: ""

# This is the message to send in chat when chat is cleared
# by a player
Chat-Cleared: "§a Chat cleared by §6%player%!"

# This is the message to send in chat when chat is cleared
# by the console
Cleared-By-Console: "§aChat cleared by console"

# This is the message send to a player if they don't have
# the required permission
No-Permission-Message: "§cYou do not have permission to clear the chat!"
